os:
  - linux
  - osx

sudo: false

language: generic

env:
- HDF5=h5py PY=2.7
- HDF5=h5py PY=3.4
- HFF5= PY=2.7
- HFF5= PY=3.4

notifications:
  email: false
  slack:
    on_success: never
    secure: kFjjqTmuOMfXQRe4XuAyJhbx6eJRVu3IdBaBtEHHQOyNVfEaXaoRCNiZxaq8gEGfJB58g0J3C2/rwCgA5Cgpu4AMHiL7gm0iFMYpez2F8RDHtDAaIZkRcxuTmebSIazdWCSwdJL3/QnsebrwyaQMVkq9NXXd30r7Gi9vahFIcTuT0riWNTvNzjzkL/MV6RCh0QSfvR1k7DZjKC76lKtvNMRB/1kLBmU1w5jxr5w+Gf/hcDX+RPr+uD2JY9t3JrAc3tzgI+wftVx8JGE2ynJvBeR+v4BSWpydM55MGmLARWlRWRCSJGojMTay3fhw8ZfKT5cYtaSvu2O1+U41Vw2BOv6HA/t8R75jhNP3SebvqsTwY4n1e3H+qISz2T8DtZnrqRKr5VnygpwLrgLbzmpnmfqAaFZIFqOWNPcXd08Mz7ocQXQbwA4xtn4Bx6D0nzeue+OE+GazWHputHsArYPIcV48WquJxszpB6blJy27xtUNbqRiio2AK54EB+hy2M66W34PQNNN2ScUf8ksJF5s34C2PGcqfgqpTw8pvfB1md4ecIUIYaA9AaNNcIv4hRliFpOaVeDm+UuQHOjEwoUXok2ktVI9iwZfOrKKgD9zE/tt1faV9OYpleoQoTgNLc3hHnQ3p7ysQi2cjjoyjvfWE7qpmnivva2NX/DUEjmtF74=

before_install:
- OS=$(if [[ "$TRAVIS_OS_NAME" = "osx" ]]; then echo "MacOSX"; else echo "Linux"; fi)
- wget "https://repo.continuum.io/miniconda/Miniconda-latest-$OS-x86_64.sh" -O miniconda.sh
- chmod +x miniconda.sh
- ./miniconda.sh -b
- PATHPREFIX=$(if [[ "$TRAVIS_OS_NAME" = "osx" ]]; then echo "/Users/travis/miniconda/bin"; else echo "/home/travis/miniconda/bin"; fi)
- export PATH=$PATHPREFIX:$PATH
- conda update --yes conda

install:
- conda install --yes python=$PY numpy scipy nose $HDF5
- pip install .

script: nosetests

